export enum CoursePermissionType {
  UpdateCourse = 'UpdateCourse',
  UpdateCourseImage = 'UpdateCourseImage',
  DeleteCourse = 'DeleteCourse',
  CreateCourseTab = 'CreateCourseTab',
  UpdateCourseTab = 'UpdateCourseTab',
  DeleteCourseTab = 'DeleteCourseTab',
  CreateCourseMaterial = 'CreateCourseMaterial',
  UpdateCourseMaterial = 'UpdateCourseMaterial',
  DeleteCourseMaterial = 'DeleteCourseMaterial',
  CreateCourseRole = 'CreateCourseRole',
  UpdateCourseRole = 'UpdateCourseRole',
  DeleteCourseRole = 'DeleteCourseRole',
  ChangeCourseMemberRole = 'ChangeCourseMemberRole',
  RemoveCourseMember = 'RemoveCourseMember',
}
