export enum PermissionType {
  ReadPermission = 'ReadPermission',
  CreateRole = 'CreateRole',
  ReadRole = 'ReadRole',
  UpdateRole = 'UpdateRole',
  DeleteRole = 'DeleteRole',
  CreateUser = 'CreateUser',
  ReadUser = 'ReadUser',
  UpdateUser = 'UpdateUser',
  DeleteUser = 'DeleteUser',
  CreateCourse = 'CreateCourse',
  ManageCourse = 'ManageCourse',
  GradeStudents = 'GradeStudents',
  ManageTestQuestions = 'ManageTestQuestions',
  UpdateOwnProfile = 'UpdateOwnProfile',
  UpdateOwnPassword = 'UpdateOwnPassword',
}
